-- SQL Dump of lahman2014_beta.mdb
-- generated by MDB Viewer 2.2.5
-- optimized for MySQL

SET NAMES 'UTF8';

DROP TABLE IF EXISTS `Appearances`;
DROP TABLE IF EXISTS `AllstarFull`;
DROP TABLE IF EXISTS `AwardsManagers`;
DROP TABLE IF EXISTS `AwardsPlayers`;
DROP TABLE IF EXISTS `AwardsShareManagers`;
DROP TABLE IF EXISTS `AwardsSharePlayers`;
DROP TABLE IF EXISTS `Batting`;
DROP TABLE IF EXISTS `BattingPost`;
DROP TABLE IF EXISTS `CollegePlaying`;
DROP TABLE IF EXISTS `Fielding`;
DROP TABLE IF EXISTS `FieldingOF`;
DROP TABLE IF EXISTS `FieldingPost`;
DROP TABLE IF EXISTS `Managers`;
DROP TABLE IF EXISTS `ManagersHalf`;
DROP TABLE IF EXISTS `Pitching`;
DROP TABLE IF EXISTS `HallOfFame`;
DROP TABLE IF EXISTS `PitchingPost`;
DROP TABLE IF EXISTS `Salaries`;
DROP TABLE IF EXISTS `SeriesPost`;
DROP TABLE IF EXISTS `TeamsFranchises`;
DROP TABLE IF EXISTS `TeamsHalf`;
DROP TABLE IF EXISTS `Master`;
DROP TABLE IF EXISTS `Teams`;
DROP TABLE IF EXISTS `Schools`;

CREATE TABLE `Master` (
    `playerID` VARCHAR(10) NOT NULL,
    `birthYear` INTEGER,
    `birthMonth` INTEGER,
    `birthDay` INTEGER,
    `birthCountry` VARCHAR(50),
    `birthState` VARCHAR(2),
    `birthCity` VARCHAR(50),
    `deathYear` INTEGER,
    `deathMonth` INTEGER,
    `deathDay` INTEGER,
    `deathCountry` VARCHAR(50),
    `deathState` VARCHAR(2),
    `deathCity` VARCHAR(50),
    `nameFirst` VARCHAR(50),
    `nameLast` VARCHAR(50),
    `nameGiven` VARCHAR(255),
    `weight` INTEGER,
    `height` DOUBLE,
    `bats` VARCHAR(1),
    `throws` VARCHAR(1),
    `debut` DATETIME,
    `finalGame` DATETIME,
    `retroID` VARCHAR(9),
    `bbrefID` VARCHAR(9),
    PRIMARY KEY (`playerID`)
) CHARACTER SET 'UTF8';



CREATE TABLE `Teams` (
    `yearID` INTEGER NOT NULL,
    `lgID` VARCHAR(2) NOT NULL,
    `teamID` VARCHAR(3) NOT NULL,
    `franchID` VARCHAR(3) NOT NULL,
    `divID` VARCHAR(1) NOT NULL,
    `Rank` INTEGER,
    `G` INTEGER,
    `Ghome` INTEGER,
    `W` INTEGER,
    `L` INTEGER,
    `DivWin` VARCHAR(1),
    `WCWin` VARCHAR(1),
    `LgWin` VARCHAR(1),
    `WSWin` VARCHAR(1),
    `R` INTEGER,
    `AB` INTEGER,
    `H` INTEGER,
    `2B` INTEGER,
    `3B` INTEGER,
    `HR` INTEGER,
    `BB` INTEGER,
    `SO` INTEGER,
    `SB` INTEGER,
    `CS` INTEGER,
    `HBP` INTEGER,
    `SF` INTEGER,
    `RA` INTEGER,
    `ER` INTEGER,
    `ERA` DOUBLE,
    `CG` INTEGER,
    `SHO` INTEGER,
    `SV` INTEGER,
    `IPouts` INTEGER,
    `HA` INTEGER,
    `HRA` INTEGER,
    `BBA` INTEGER,
    `SOA` INTEGER,
    `E` INTEGER,
    `DP` INTEGER,
    `FP` DOUBLE,
    `name` VARCHAR(50),
    `park` VARCHAR(255),
    `attendance` INTEGER,
    `BPF` INTEGER,
    `PPF` INTEGER,
    `teamIDBR` VARCHAR(3),
    `teamIDlahman45` VARCHAR(3),
    `teamIDretro` VARCHAR(3),
    PRIMARY KEY ( `yearID`, `lgID`, `teamID`, `divID`, `franchID` )
) CHARACTER SET 'UTF8';



CREATE TABLE `Schools` (
    `schoolID` VARCHAR(15) NOT NULL,
    `name_full` VARCHAR(255),
    `city` VARCHAR(55),
    `state` VARCHAR(55),
    `country` VARCHAR(55),
    PRIMARY KEY (`schoolID`)
) CHARACTER SET 'UTF8';



CREATE TABLE `TeamsHalf` (
    `yearID` INTEGER NOT NULL,
    `lgID` VARCHAR(2) NOT NULL,
    `teamID` VARCHAR(3)NOT NULL,
    `Half` VARCHAR(1) NOT NULL,
    `divID` VARCHAR(1),
    `DivWin` VARCHAR(1),
    `Rank` INTEGER,
    `G` INTEGER,
    `W` INTEGER,
    `L` INTEGER,
    PRIMARY KEY ( `yearID`, `teamID`, `lgID`, `Half` ),
    FOREIGN KEY (`teamID`) references Teams(`teamID`) ON DELETE CASCADE,
    FOREIGN KEY (`yearID`) references Teams(`yearID`) ON DELETE CASCADE
) CHARACTER SET 'UTF8';